CREATE TABLE MODULE(
	ID INT NOT NULL PRIMARY KEY  AUTO_INCREMENT ,
	MODULECODE VARCHAR(100) NOT NULL,
	MODULENAME VARCHAR(100) NOT NULL,
    CREDITS INT NOT NULL,
    HOURSPERWEEK INT NOT NULL,
    NUMBEROFWEEK INT NOT NULL,
    STARTDATE DATATIME NOT NULL,
    USERID INT NOT NULL
);