CREATE TABLE TB_TABLE(
	ID INT NOT NULL PRIMARY KEY  AUTO_INCREMENT ,
	STUDENTNUMBER VARCHAR(100) NOT NULL,
	STUDENTNAME VARCHAR(100) NOT NULL,
    STUDENTSURNAMEINT VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    COMFIRMPASSWORD VARCHAR(100) NOT NULL,
    
);